### ISSUE TITLE
Package stopped working

### ISSUE THREAD

**Issue by MathijsKlaassen** [tobigs/mfinancials#2]
Hi,

Since a week or so the package has stopped working. I think the issue is that it is unable to retrieve data from the morningstar website.

The code that i'm running is as follow, for example for adobe stock:

adbe = mf.Ticker('adbe')
adbe_ratios = adbe.keyRatios.T
adbe = adbe.financials.T

error:
AttributeError: 'NoneType' object has no attribute 'T'

The following statements are printed:
Unable to get keyRatios data for adbe
Check http://financials.morningstar.com/ratios/r.html?t=adbe

Kind regards

**Comment by tobigs** [comment]
Unfortunately Morningstar decided to shut down the datasource.

**Comment by tobigs** [comment]
Unfortunately Morningstar decided to shut down the datasource.
